### ISSUE TITLE
image build broken, urbackup-server not installed

### ISSUE THREAD

**Issue by tshirtman** [firsttris/urbackup-docker#1]
starting the image fails with 

    container_linux.go:247: starting container process caused "exec: \"/usr/bin/urbackupsrv\": stat /usr/bin/urbackupsrv: no such file or directory"

which had me scratch my head, also, since it's the entry point, i can't start it with bash to investigate, but the build log here, indicates that the package doesn't install correctly, and is removed by `apt install -y -f`

https://hub.docker.com/r/tristanteu/urbackup-docker/builds/b22g8sjrg3263x9hhtus5s/

**Comment by firsttris** [comment]
thx for reporting. if i have some free time i will fix the build. if you have already fixed it - please share your code :+1:

**Comment by firsttris** [comment]
i fixed the build ⚡️
