### ISSUE TITLE
LAN Client Discovery needs net: "host"

### ISSUE THREAD

**Issue by MeFisto94** [firsttris/urbackup-docker#4]
So I noticed that the client discovery does not work when you are not using `net: "host"`.
I've read that urbackup sends a broadcast udp on every assigned network interface's subnet, so maybe something goes wrong like the content of the discovery packet not getting NAT'ed.

So it would be nice if you could edit the Readme with a hint that in order for LAN discovery to work, one needs the net-host mode.

Maybe one could also find out a way to fix it so one does not need the net-host mode?

**Comment by firsttris** [comment]
the example in the Readme includes --net="host"
https://github.com/firsttris/urbackup-docker#run

**Comment by MeFisto94** [comment]
That's true, but I meant it doesn't explicitly say that this is required for client discovery to work, that's what confused me (as I prefer to not use --net host).
So it's nit picking but it would be nice to have :)

**Comment by firsttris** [comment]
If you like you can change the readme and create pr :+1:

**Comment by MeFisto94** [comment]
I completely forgot about that issue, I will see if I have the time for a PR before my vacation.
