### ISSUE TITLE
Update Image (Auto-Build?)

### ISSUE THREAD

**Issue by MeFisto94** [firsttris/urbackup-docker#6]
So, the Container is on Version 2.2.11, where 2.3.7 is out.
Instead of manually updating the container everytime, we should look into some automatism.
I don't know what the docker hub exactly provides there, but essentially one could use:

http://hndl.urbackup.org/Server/latest/ (or https://www.urbackup.org/downloads/Server/latest as in the Dockerfile, they seem to be identical).

There, RegEx for `<a href="urbackup-server_2.3.8_amd64.deb">urbackup-server_2.3.8_amd64.deb</a>`, technically `urbackup-server_(.*)_amd64.deb` should be enough to grab the version.

Now what I don't know is how one could automate this? A Cron Job and when the extracted version doesn't match what one already knows, just change this in the VERSION Dockerfile and auto-commit? 

Edit: It doesn't belong here, but `RUN DEBIAN_FRONTEND=noninteractive dpkg -i /root/urbackup.deb  || true` -> Is this intentional? Because the `|| true` statement builds the image even when the installation fails.

**Comment by vidschofelix** [comment]
Have a look at https://github.com/firsttris/urbackup-docker/pull/5. 
i already implemented the automatic use of the latest version. All we need is a trigger that rebuilds the container from time to time. 
btw: 2.3.8 is out ;)
@firsttris : I got [this](https://github.com/tozd/docker-hub-build-trigger/blob/master/etc/cron.daily/docker-hub-build-trigger) curl to work, so maybe you (or i) can trigger your build daily.

**Comment by firsttris** [comment]
actually i think i had auto-build activated in docker-hub, but i had to re-link my github account.

its also possible to trigger the build by sending a POST to this url

^remove-url

**Comment by vidschofelix** [comment]
Auto-build only triggers on new commits on github. 
I added it to my autobuild cron, it will be build daily.
Maybe you should remove the url, i think trigger URLs should not be public...
