### ISSUE TITLE
Add BTRFS Support

### ISSUE THREAD

**Issue by geraldpublic** [firsttris/urbackup-docker#7]
Hello,

thanks for this container, one additional feature could be added quite easy.
Please add following in the dockerfile and in the docker-compose Info to support native BTRFS Snapshots on BTRFS Backup Volumes 
**Dockerfile**: install the "btrfs-tools"
RUN apt-get install sqlite3 libcrypto++6 libcurl3 libfuse2 wget btrfs-tools -y
**Info for docker-compose file**
    cap_add:
     - SYS_ADMIN

Thanks in Advance
greets 
Gerald

**Comment by firsttris** [comment]
Hey @geraldpublic 

could you create a pull-request?

**Comment by geraldpublic** [comment]
hey, sure no problem - done
